---
apiVersion: v1
kind: Service
metadata:
  name: alarm-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/alarms"
spec:
  selector:
    app:  alarm-backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
