---
apiVersion: v1
kind: Service
metadata:
  name: mypage-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/mypages"
spec:
  selector:
    app:  mypage-backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
